gpu_num: [0, 1, 2, 3, 4, 5, 6, 7]
random_seed: 0

#model
model:
  lr: 0.00001
  batch_size: 4
  epochs: 1
  bert_model: allenai/longformer-base-4096
  optimizer: adamw
  gradient_clip: 1
  gradient_accumulation: 4


# data and model path
data:
  training_set: data/v3/train.jsonl
  dev_set: data/v3/dev.jsonl
  test_set: data/v3/test.jsonl


full_doc: true
model_path: /net/nfs.cs/s2-research/ariec/scico/models
log: logs


# inference
checkpoint_multiclass: path-to-multiclass-ckpt
checkpoint_coref: path-to-binary-coref-ckpt
checkpoint_hypernym: path-hierarchy-model-ckpt
agg_threshold: 0.6  # for agglomerative clustering
hypernym_threshold: 0.4 # for hypernym scores
save_path: path-to-save-dir
